In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [42]:
claim_dataset= pd.read_csv('insurance_claims.csv')

In [43]:
claim_dataset.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN

In [44]:
claim_dataset.shape

(1000, 40)

In [45]:
claim_dataset.isnull().sum()

months_as_customer                0
age                               0
policy_number                     0
policy_bind_date                  0
policy_state                      0
policy_csl                        0
policy_deductable                 0
policy_annual_premium             0
umbrella_limit                    0
insured_zip                       0
insured_sex                       0
insured_education_level           0
insured_occupation                0
insured_hobbies                   0
insured_relationship              0
capital-gains                     0
capital-loss                      0
incident_date                     0
incident_type                     0
collision_type                    0
incident_severity                 0
authorities_contacted            91
incident_state                    0
incident_city                     0
incident_location                 0
incident_hour_of_the_day          0
number_of_vehicles_involved       0
property_damage                   0
bodily_injuries                   0
witnesses                         0
police_report_available           0
total_claim_amount                0
injury_claim                      0
property_claim                    0
vehicle_claim                     0
auto_make                         0
auto_model                        0
auto_year                         0
fraud_reported                    0
_c39                           1000
dtype: int64

In [46]:
claim_dataset['authorities_contacted'].value_counts()

authorities_contacted
Police       292
Fire         223
Other        198
Ambulance    196
Name: count, dtype: int64

In [47]:
from sklearn.preprocessing import LabelEncoder

In [48]:
label_encoder = LabelEncoder()

In [49]:
claim_dataset['authorities_contacted']=label_encoder.fit_transform(claim_dataset["authorities_contacted"])

In [50]:
claim_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   object
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   object
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        1000 non-null   int32
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: float64(2), int32(1), int64(17), object(20)
memory usage: 308.7+ KB

In [51]:
claim_dataset.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN

In [97]:
claim_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   datetime64[ns]
 4   policy_state                 1000 non-null   int64
 5   policy_csl                   1000 non-null   int64
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   int32
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   int64
 11  insured_education_level      1000 non-null   int64
 12  insured_occupation           1000 non-null   int64
 13  insured_hobbies              1000 non-null   int64
 14  insured_relationship         1000 non-null   int64
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   datetime64[ns]
 18  incident_type                1000 non-null   int64
 19  collision_type               1000 non-null   int64
 20  incident_severity            1000 non-null   int64
 21  authorities_contacted        1000 non-null   int32
 22  incident_state               1000 non-null   int64
 23  incident_city                1000 non-null   int64
 24  incident_location            1000 non-null   int64
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   int64
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   int64
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   int64
 36  auto_model                   1000 non-null   int64
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   int64
dtypes: datetime64[ns](2), int32(2), int64(35)
memory usage: 297.0 KB

In [58]:
claim_dataset.select_dtypes(include="float64").columns

Index(['policy_annual_premium', '_c39'], dtype='object')

In [59]:
claim_dataset=claim_dataset.drop('_c39',axis=1)

In [66]:
claim_dataset=claim_dataset.astype({"policy_annual_premium":'str'})

print(claim_dataset.dtypes)

months_as_customer                      int64
age                                     int64
policy_number                           int64
policy_bind_date               datetime64[ns]
policy_state                           object
policy_csl                             object
policy_deductable                       int64
policy_annual_premium                  object
umbrella_limit                          int64
insured_zip                             int64
insured_sex                            object
insured_education_level                object
insured_occupation                     object
insured_hobbies                        object
insured_relationship                   object
capital-gains                           int64
capital-loss                            int64
incident_date                  datetime64[ns]
incident_type                          object
collision_type                         object
incident_severity                      object
authorities_contacted                   int32
incident_state                         object
incident_city                          object
incident_location                      object
incident_hour_of_the_day                int64
number_of_vehicles_involved             int64
property_damage                        object
bodily_injuries                         int64
witnesses                               int64
police_report_available                object
total_claim_amount                      int64
injury_claim                            int64
property_claim                          int64
vehicle_claim                           int64
auto_make                              object
auto_model                             object
auto_year                               int64
fraud_reported                         object
dtype: object

In [67]:
claim_dataset.select_dtypes(include="object").columns

Index(['policy_state', 'policy_csl', 'policy_annual_premium', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'incident_type', 'collision_type',
       'incident_severity', 'incident_state', 'incident_city',
       'incident_location', 'property_damage', 'police_report_available',
       'auto_make', 'auto_model', 'fraud_reported'],
      dtype='object')

In [99]:
claim_dataset['policy_state']=label_encoder.fit_transform(claim_dataset["policy_state"])
claim_dataset['policy_csl']=label_encoder.fit_transform(claim_dataset["policy_csl"])
claim_dataset['insured_sex']=label_encoder.fit_transform(claim_dataset["insured_sex"])
claim_dataset['insured_education_level']=label_encoder.fit_transform(claim_dataset["insured_education_level"])
claim_dataset['insured_occupation']=label_encoder.fit_transform(claim_dataset["insured_occupation"])
claim_dataset['insured_hobbies']=label_encoder.fit_transform(claim_dataset["insured_hobbies"])
claim_dataset['insured_relationship']=label_encoder.fit_transform(claim_dataset["insured_relationship"])
claim_dataset['incident_type']=label_encoder.fit_transform(claim_dataset["incident_type"])
claim_dataset['collision_type']=label_encoder.fit_transform(claim_dataset["collision_type"])
claim_dataset['incident_severity']=label_encoder.fit_transform(claim_dataset["incident_severity"])
claim_dataset['incident_state']=label_encoder.fit_transform(claim_dataset["incident_state"])
claim_dataset['incident_city']=label_encoder.fit_transform(claim_dataset["incident_city"])
claim_dataset['incident_location']=label_encoder.fit_transform(claim_dataset["incident_location"])
claim_dataset['property_damage']=label_encoder.fit_transform(claim_dataset["property_damage"])
claim_dataset['police_report_available']=label_encoder.fit_transform(claim_dataset["police_report_available"])
claim_dataset['auto_make']=label_encoder.fit_transform(claim_dataset["auto_make"])
claim_dataset['auto_model']=label_encoder.fit_transform(claim_dataset["auto_model"])
claim_dataset['fraud_reported']=label_encoder.fit_transform(claim_dataset["fraud_reported"])

In [100]:
claim_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   datetime64[ns]
 4   policy_state                 1000 non-null   int64
 5   policy_csl                   1000 non-null   int64
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   int32
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   int64
 11  insured_education_level      1000 non-null   int64
 12  insured_occupation           1000 non-null   int64
 13  insured_hobbies              1000 non-null   int64
 14  insured_relationship         1000 non-null   int64
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   datetime64[ns]
 18  incident_type                1000 non-null   int64
 19  collision_type               1000 non-null   int64
 20  incident_severity            1000 non-null   int64
 21  authorities_contacted        1000 non-null   int32
 22  incident_state               1000 non-null   int64
 23  incident_city                1000 non-null   int64
 24  incident_location            1000 non-null   int64
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   int64
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   int64
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   int64
 36  auto_model                   1000 non-null   int64
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   int64
dtypes: datetime64[ns](2), int32(2), int64(35)
memory usage: 297.0 KB

In [101]:
claim_dataset.shape

(1000, 39)

In [102]:
claim_dataset.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,328,48,521585,2014-10-17,2,1,1000,579,0,466132,...,2,2,71610,6510,13020,52080,10,1,2004,1
1,228,42,342868,2006-06-27,1,1,2000,243,5000000,468176,...,0,0,5070,780,780,3510,8,12,2007,1
2,134,29,687698,2000-09-06,2,0,2000,587,5000000,430632,...,3,1,34650,7700,3850,23100,4,30,2007,0
3,256,41,227811,1990-05-25,0,1,2000,590,6000000,608117,...,2,1,63400,6340,6340,50720,3,34,2014,1
4,228,44,367455,2014-06-06,0,2,1000,749,6000000,610706,...,1,1,6500,1300,650,4550,0,31,2009,0

In [116]:
X=claim_dataset.drop(['fraud_reported','policy_bind_date','incident_date'],axis=1)
Y=claim_dataset['fraud_reported']

In [117]:
print(X)
print(Y)

     months_as_customer  age  policy_number  policy_state  policy_csl  \
0                   328   48         521585             2           1
1                   228   42         342868             1           1
2                   134   29         687698             2           0
3                   256   41         227811             0           1
4                   228   44         367455             0           2
..                  ...  ...            ...           ...         ...
995                   3   38         941851             2           2
996                 285   41         186934             0           0
997                 130   34         918516             2           1
998                 458   62         533940             0           2
999                 456   60         556080             2           1

     policy_deductable  policy_annual_premium  umbrella_limit  insured_zip  \
0                 1000                    579               0       466132
1                 2000                    243         5000000       468176
2                 2000                    587         5000000       430632
3                 2000                    590         6000000       608117
4                 1000                    749         6000000       610706
..                 ...                    ...             ...          ...
995               1000                    424               0       431289
996               1000                    612               0       608177
997                500                    538         3000000       442797
998               2000                    499         5000000       441714
999               1000                    857               0       612260

     insured_sex  ...  bodily_injuries  witnesses  police_report_available  \
0              1  ...                1          2                        2
1              1  ...                0          0                        0
2              0  ...                2          3                        1
3              0  ...                1          2                        1
4              1  ...                0          1                        1
..           ...  ...              ...        ...                      ...
995            0  ...                0          1                        0
996            0  ...                2          3                        0
997            0  ...                2          3                        2
998            1  ...                0          1                        2
999            0  ...                0          3                        0

     total_claim_amount  injury_claim  property_claim  vehicle_claim  \
0                 71610          6510           13020          52080
1                  5070           780             780           3510
2                 34650          7700            3850          23100
3                 63400          6340            6340          50720
4                  6500          1300             650           4550
..                  ...           ...             ...            ...
995               87200         17440            8720          61040
996              108480         18080           18080          72320
997               67500          7500            7500          52500
998               46980          5220            5220          36540
999                5060           460             920           3680

     auto_make  auto_model  auto_year
0           10           1       2004
1            8          12       2007
2            4          30       2007
3            3          34       2014
4            0          31       2009
..         ...         ...        ...
995          6           6       2006
996         13          28       2015
997         11          19       1996
998          1           5       1998
999          8          12       2007

[1000 rows x 36 columns]
0      1
1      1
2      0
3      1
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: fraud_reported, Length: 1000, dtype: int64

In [118]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=2)

In [119]:
print(Y.shape, Y_train.shape, Y_test.shape)

(1000,) (800,) (200,)

In [120]:
from sklearn.ensemble import RandomForestClassifier

In [121]:
model = RandomForestClassifier()

In [122]:
model.fit(X_train, Y_train)

RandomForestClassifier()

In [123]:
X_test_prediction = model.predict(X_test)

data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [124]:
print('Accuracy:', data_accuracy)

Accuracy: 0.795